version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec

linters-settings:
  gosec:
    excludes:
      - G304

issues:
  exclude-rules:
    - path: ".*_test\\.go"
      linters:
        - errcheck
        - gosec
